# Generated by Django 4.2.13 on 2024-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group',
            new_name='name',
        ),
    ]
