# Generated by Django 4.2.13 on 2024-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_group_groups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
