# Generated by Django 4.2.13 on 2024-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_summ_debts_sum_rename_summ_payments_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='image',
            field=models.ImageField(default=-1, upload_to=''),
            preserve_default=False,
        ),
    ]
