# Generated by Django 4.2.13 on 2024-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_debts_created_at_alter_groups_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='finished_at',
            field=models.DateField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='image',
            field=models.ImageField(upload_to='data/'),
        ),
    ]
