# Generated by Django 4.2.13 on 2024-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_groups_finished_at_alter_payments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='groups',
            name='finished',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
