# Generated by Django 4.2.13 on 2024-07-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_students_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debts',
            old_name='summ',
            new_name='sum',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='summ',
            new_name='sum',
        ),
    ]
