# Generated by Django 4.2.13 on 2024-07-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_groups_finished_at_groups_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='finished',
        ),
    ]
